SELECT * FROM TB_UF;
SELECT * FROM TB_MUNICIPIO;
SELECT * FROM TB_CIDADE;
SELECT * FROM TB_BAIRRO;
SELECT * FROM TB_LOGRADOURO;
SELECT * FROM TB_BAIRRO_LOGRADOURO;

SELECT * FROM TB_UF A
 JOIN TB_MUNICIPIO B ON A.SIGLA_UF = B.SIGLA_UF
 JOIN TB_CIDADE C ON A.SIGLA_UF = C.SIGLA_UF
 WHERE C.CIDADE = 'Belo Horizonte'
    AND A.SIGLA_UF = 'MG';
 
 
 SELECT * FROM TB_CIDADE A
 JOIN TB_BAIRRO B ON A.PID = B.PID_CIDADE
 JOIN TB_LOGRADOURO C ON B.CEP = C.CEP
 WHERE INITCAP(C.TIPO) = 'Rua'
    AND INITCAP(A.CIDADE) = 'São Paulo';
    
SELECT * FROM TB_CIDADE A
 JOIN TB_BAIRRO B ON A.PID = B.PID_CIDADE
 JOIN TB_LOGRADOURO C ON B.CEP = C.CEP
 WHERE A.SIGLA_UF = 'MG';







select MDSYS.SDO_GEOMETRY('POINT('+LATITUDE+','+LONGITUDE+ ')',4326) WKT FROM TB_MUNICIPIO;

select MDSYS.SDO_GEOMETRY ('POINT(' + CAST([LATITUDE] AS VARCHAR(20)) + ' ' + CAST([LONGITUDE] AS VARCHAR(20)) + ')', 4326) WKT FROM TB_MUNICIPIO;


truncate table "SYSTEM"."TB_BAIRRO" drop storage;


