CREATE TABLE TB_UF
(   SIGLA_UF VARCHAR2(2) NOT NULL,
    COD_IBGE VARCHAR2(10) NOT NULL, 
    ESTADO  VARCHAR2(30),
    REGIAO VARCHAR(20)    
);

ALTER TABLE TB_UF 
ADD CONSTRAINT PK_TB_UF
PRIMARY KEY (SIGLA_UF);


CREATE TABLE TB_MUNICIPIO
(   PID NUMBER NOT NULL,
    SIGLA_UF VARCHAR2(2) NOT NULL, 
    COD_IBGE VARCHAR2(10) NOT NULL,
    MUNICPIO VARCHAR2(30) NOT NULL,
    LATITUDE VARCHAR2(30),
    LONGITUDE VARCHAR2(30)
);

ALTER TABLE TB_MUNICIPIO
ADD CONSTRAINT PK_TB_MUNICIPIO
PRIMARY KEY (PID);

ALTER TABLE TB_MUNICIPIO
ADD CONSTRAINT FK_MUNICIPIO_UF
FOREIGN KEY (SIGLA_UF)
REFERENCES TB_UF(SIGLA_UF);

COMMIT;


-- Ainda não foram criadas
CREATE TABLE TB_BAIRRO
(   PID NUMBER NOT NULL, 
    SIGLA_UF VARCHAR2(2) NOT NULL,
    ID_MUNICIPIO NUMBER NOT NULL,
    BAIRRO VARCHAR2(50),
    GEOMETRIA MDSYS.SDO_GEOMETRY
);

ALTER TABLE TB_BAIRRO
ADD CONSTRAINT PK_TB_BAIRRO
PRIMARY KEY (PID);

ALTER TABLE TB_BAIRRO
ADD CONSTRAINT FK_BAIRRO_UF
FOREIGN KEY (SIGLA_UF)
REFERENCES TB_UF (SIGLA_UF);

ALTER TABLE TB_BAIRRO
ADD CONSTRAINT FK_MUNICIPIO_BAIRRO
FOREIGN KEY (ID_MUNICIPIO)
REFERENCES TB_MUNICIPIO (PID);


CREATE TABLE TB_LOGRADOURO
(   PID NUMBER NOT NULL,
    SIGLA_UF VARCHAR2(2) NOT NULL,
    ID_MUNICIPIO NUMBER NOT NULL,
    LOGRADOURO VARCHAR2(100)
);

ALTER TABLE TB_LOGRADOURO
ADD CONSTRAINT PK_TB_LOGRADOURO
PRIMARY KEY (PID);

ALTER TABLE TB_LOGRADOURO
ADD CONSTRAINT FK_TB_LOGRADOURO_UF
FOREIGN KEY (SIGLA_UF)
REFERENCES TB_UF(SIGLA_UF);

ALTER TABLE TB_LOGRADOURO
ADD CONSTRAINT FK_TB_LOGRADOURO_MUNICIPIO
FOREIGN KEY (ID_MUNICIPIO)
REFERENCES TB_MUNICIPIO(PID);


CREATE TABLE TB_BAIRRO_LOGRADOURO
(   PID NUMBER NOT NULL,
    ID_LOGRADOURO NUMBER NOT NULL,
    ID_BAIRRO NUMBER NOT NULL
);


ALTER TABLE TB_BAIRRO_LOGRADOURO
ADD CONSTRAINT FK_TB_BAIRRO_LOGRADOURO_BAIRRO
FOREIGN KEY (ID_BAIRRO)
REFERENCES TB_BAIRRO (PID);


ALTER TABLE TB_BAIRRO_LOGRADOURO
ADD CONSTRAINT FK_TB_BAIRRO_LOGRADOURO_LOGRADOURO
FOREIGN KEY (ID_LOGRADOURO)
REFERENCES TB_LOGRADOURO (PID);

COMMIT;

DROP TABLE TB_UF;
DROP TABLE TB_MUNICIPIO;
DROP TABLE TB_BAIRRO;
DROP TABLE TB_LOGRADOURO;
DROP TABLE TB_BAIRRO_LOGRADOURO;
