SELECT * FROM tb_uf;
SELECT * FROM tb_municipio;


-- sequencia da pk de municipio
CREATE SEQUENCE SEQ_PID_MUNICIPIO
START WITH 1 
INCREMENT BY 1;

-- sequencial de PID
CREATE OR REPLACE TRIGGER PID_MUNICIPIO
BEFORE INSERT ON TB_MUNICIPIO FOR EACH ROW
BEGIN
    IF (:NEW.PID IS NULL) THEN
        :NEW.PID := SYSTEM.SEQ_PID_MUNICIPIO.NEXTVAL;
    END IF;
END;
/  

COMMIT;