-- SEQUENCIA DO PID DE TB_MUNICIPIO
CREATE SEQUENCE SEQ_PID_MUNICIPIO START WITH 1 INCREMENT BY 1;

-- SEQUENCIA DO PID DE TB_BAIRRO
CREATE SEQUENCE SEQ_PID_BAIRRO START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_PID_CIDADE START WITH 1 INCREMENT BY 1;

DROP SEQUENCE SEQ_PID_CIDADE;

