CREATE OR REPLACE VIEW VW_MUNICIPIO_UF ("ESTADO_UF","IBGE_UF","REGIAO","IBGE_MUNICIPIO","MUNICIPIO","LATITUDE","LONGITUDE") AS 
SELECT 
    A.ESTADO||'-'||A.SIGLA_UF ESTADO_UF,
    A.COD_IBGE IBGE_UF,
    A.REGIAO,
    B.COD_IBGE IBGE_MUNICIPIO,
    B.MUNICIPIO,
    B.LATITUDE,
    B.LONGITUDE
FROM TB_UF A 
JOIN TB_MUNICIPIO B  ON A.SIGLA_UF = B.SIGLA_UF;
