-- MORADORES
CREATE TABLE TB_MORADORES(
    P_MORADOR NUMBER NOT NULL,
    NOME VARCHAR2(100),
    GENERO CHAR(1) CHECK (GENERO IN('M','F')),
    DATA_NASCIMENTO DATE,
    CONSTRAINT  PK_MORADOR PRIMARY KEY (P_MORADOR)
);
 
 

CREATE SEQUENCE SQ_MORADORES START WITH 1 INCREMENT BY 1;


CREATE OR REPLACE TRIGGER TR_MORADORES_PK
BEFORE INSERT ON TB_MORADORES FOR EACH ROW
BEGIN
    IF :NEW.P_MORADOR IS NULL THEN
        :NEW.P_MORADOR := SQ_MORADORES.NEXTVAL;
    END IF;
END;
/