CREATE OR REPLACE PROCEDURE SP_INSERIR_LOGRADOURO
(P_SIGLA_UF VARCHAR2,P_CIDADE VARCHAR2,P_LOGRADOURO VARCHAR2,P_CEP NUMBER,P_TIPO VARCHAR2)
IS
    VID_CIDADE NUMBER;
BEGIN
    VID_CIDADE := FNC_FK_PID_CIDADE(P_CIDADE);
    INSERT INTO TB_LOGRADOURO (SIGLA_UF,PID_CIDADE,LOGRADOURO,CEP,TIPO) 
        VALUES (P_SIGLA_UF,VID_CIDADE,P_LOGRADOURO,P_CEP,P_TIPO);
END;
/