CREATE OR REPLACE PROCEDURE SP_INSERIR_BAIRRO
(P_SIGLA_UF VARCHAR2,P_BAIRRO VARCHAR2,P_CIDADE VARCHAR2,P_CEP NUMBER,P_LATITUDE VARCHAR2,P_LONGITUDE VARCHAR2)
IS
 VCIDADE NUMBER;
BEGIN
    VCIDADE := FNC_FK_PID_CIDADE(P_CIDADE);
    
    INSERT INTO TB_BAIRRO (SIGLA_UF,BAIRRO,PID_CIDADE,CEP,LATITUDE,LONGITUDE)
        VALUES (P_SIGLA_UF,P_BAIRRO,VCIDADE,P_CEP,P_LATITUDE,P_LONGITUDE);
END;
/
