-- TRIGGER DO PID DE TB_MUNICIPIO
CREATE OR REPLACE TRIGGER PID_MUNICIPIO
BEFORE INSERT ON TB_MUNICIPIO FOR EACH ROW
BEGIN
    IF (:NEW.PID IS NULL) THEN
        :NEW.PID := SYSTEM.SEQ_PID_MUNICIPIO.NEXTVAL;
    END IF;
END;
/  

-- TRIGGER DO PID DE TB_CIDADE
CREATE OR REPLACE TRIGGER TR_PID_CIDADE
BEFORE INSERT ON TB_CIDADE FOR EACH ROW
BEGIN
    IF (:NEW.PID IS NULL) THEN
        :NEW.PID := SYSTEM.SEQ_PID_CIDADE.NEXTVAL;
    END IF;
END;
/  

-- TRIGGER DO PID DE TB_BAIRRO
CREATE OR REPLACE TRIGGER TR_PID_BAIRRO
BEFORE INSERT ON TB_BAIRRO FOR EACH ROW
BEGIN
    IF (:NEW.PID IS NULL) THEN
        :NEW.PID := SYSTEM.SEQ_PID_BAIRRO.NEXTVAL;
    END IF;
END;
/ 

-- TRIGGER DO PID DE TB_BAIRRO
CREATE OR REPLACE TRIGGER TR_PID_LOGRADOURO
BEFORE INSERT ON TB_LOGRADOURO FOR EACH ROW
BEGIN
    IF (:NEW.PID IS NULL) THEN
        :NEW.PID := SYSTEM.SEQ_PID_LOGRADOURO.NEXTVAL;
    END IF;
END;
/  

CREATE OR REPLACE TRIGGER TR_PID_BAIRRO_LOGRADOURO
BEFORE INSERT ON TB_BAIRRO_LOGRADOURO FOR EACH ROW
BEGIN
    IF (:NEW.PID IS NULL) THEN
        :NEW.PID := SYSTEM.SEQ_PID_BAIRRO_LOGRADOURO.NEXTVAL;
    END IF;
END;
/  


CREATE OR REPLACE TRIGGER TR_TB_BAIRRO_LOGRADOURO
AFTER INSERT ON TB_BAIRRO FOR EACH ROW
DECLARE
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO TB_BAIRRO_LOGRADOURO (PID_BAIRRO,PID_LOGRADOURO)
        SELECT A.PID, B.PID FROM TB_BAIRRO A
        JOIN TB_LOGRADOURO B ON A.CEP = B.CEP;
    COMMIT;
END;
/



