-- TRIGGER DO PID DE TB_MUNICIPIO
CREATE OR REPLACE TRIGGER PID_MUNICIPIO
BEFORE INSERT ON TB_MUNICIPIO FOR EACH ROW
BEGIN
    IF (:NEW.PID IS NULL) THEN
        :NEW.PID := SYSTEM.SEQ_PID_MUNICIPIO.NEXTVAL;
    END IF;
END;
/  

-- TRIGGER DO PID DE TB_BAIRRO
CREATE OR REPLACE TRIGGER TR_PID_BAIRRO
BEFORE INSERT ON TB_BAIRRO FOR EACH ROW
BEGIN
    IF (:NEW.PID IS NULL) THEN
        :NEW.PID := SYSTEM.SEQ_PID_BAIRRO.NEXTVAL;
    END IF;
END;
/ 

-- TRIGGER DO PID DE TB_BAIRRO
CREATE OR REPLACE TRIGGER TR_PID_CIDADE
BEFORE INSERT ON TB_CIDADE FOR EACH ROW
BEGIN
    IF (:NEW.PID IS NULL) THEN
        :NEW.PID := SYSTEM.SEQ_PID_CIDADE.NEXTVAL;
    END IF;
END;
/  

