CREATE TABLE TB_UF( 
    P_UF VARCHAR2(2) NOT NULL,
    COD_IBGE VARCHAR2(10) NOT NULL, 
    ESTADO  VARCHAR2(30),
    REGIAO VARCHAR(20),
    CONSTRAINT PK_UF PRIMARY KEY (P_UF)
);


CREATE TABLE TB_CIDADE(
    P_CIDADE NUMBER NOT NULL,
    COD_IBGE NUMBER,
    CIDADE VARCHAR2(100),
    F_UF VARCHAR2(2) NOT NULL,
    CIDADE_AREA NUMBER,
    CONSTRAINT PK_CIDADE PRIMARY KEY (P_CIDADE),
    CONSTRAINT FK_CIDADE_UF FOREIGN KEY(F_UF) REFERENCES TB_UF(P_UF)
);


CREATE TABLE TB_MUNICIPIO(
    P_MUNICIPIO NUMBER NOT NULL,
    F_UF VARCHAR2(2) NOT NULL, 
    COD_IBGE VARCHAR2(10) NOT NULL,
    MUNICIPIO VARCHAR2(30) NOT NULL,
    LATITUDE VARCHAR2(30),
    LONGITUDE VARCHAR2(30),
    CONSTRAINT PK_MUNICIPIO PRIMARY KEY (P_MUNICIPIO),
    CONSTRAINT FK_MUNICIPIO_UF FOREIGN KEY (F_UF) REFERENCES TB_UF (P_UF)
);


CREATE TABLE TB_BAIRRO
(   P_BAIRRO NUMBER NOT NULL, 
    F_UF VARCHAR2(2) NOT NULL,
    BAIRRO VARCHAR2(100),
    F_CIDADE NUMBER NOT NULL,
    CEP VARCHAR2(9),
    LATITUDE VARCHAR2(30),
    LONGITUDE VARCHAR2(30),
    CONSTRAINT PK_BAIRRO PRIMARY KEY (P_BAIRRO),
    CONSTRAINT FK_BAIRRO_UF FOREIGN KEY (F_UF) REFERENCES TB_UF (P_UF),
    CONSTRAINT FK_BAIRRO_CIDADE FOREIGN KEY (F_CIDADE) REFERENCES TB_CIDADE (P_CIDADE)
);


CREATE TABLE TB_LOGRADOURO(
    P_LOGRADOURO NUMBER NOT NULL,
    F_UF VARCHAR2(2) NOT NULL,
    F_CIDADE NUMBER NOT NULL,
    LOGRADOURO VARCHAR2(100),
    CEP VARCHAR2(9),
    TIPO VARCHAR2(100),
    CONSTRAINT PK_LOGRADOURO PRIMARY KEY (P_LOGRADOURO),
    CONSTRAINT FK_LOGRADOURO_UF FOREIGN KEY (F_UF) REFERENCES TB_UF (P_UF),
    CONSTRAINT FK_LOGRADOURO_CIDADE FOREIGN KEY (F_CIDADE) REFERENCES TB_CIDADE(P_CIDADE)
);

CREATE TABLE TB_BAIRRO_LOGRADOURO (
    P_BAIRRO_LOGRADOURO NUMBER NOT NULL,
    F_BAIRRO NUMBER NOT NULL,
    F_LOGRADOURO NUMBER NOT NULL,
    CONSTRAINT PK_BAIRRO_LOGRADOURO PRIMARY KEY (P_BAIRRO_LOGRADOURO),
    CONSTRAINT FK_BAIRRO_BAIRRO_LOGRADOURO FOREIGN KEY (F_BAIRRO) REFERENCES TB_BAIRRO(P_BAIRRO),
    CONSTRAINT FK_LOGRADOURO_BAIRRO_LOGRADOURO FOREIGN KEY (F_LOGRADOURO) REFERENCES TB_LOGRADOURO (P_LOGRADOURO)
);


-- MORADORES
CREATE TABLE TB_MORADORES(
    P_MORADOR NUMBER NOT NULL,
    NOME VARCHAR2(100),
    GENERO CHAR(1) CHECK (GENERO IN('M','F')),
    DATA_NASCIMENTO DATE,
    CONSTRAINT  PK_MORADOR PRIMARY KEY (P_MORADOR)
);
 
 