CREATE TABLE TB_UF
(   SIGLA_UF VARCHAR2(2) NOT NULL,
    COD_IBGE VARCHAR2(10) NOT NULL, 
    ESTADO  VARCHAR2(30),
    REGIAO VARCHAR(20)    
);

ALTER TABLE TB_UF 
ADD CONSTRAINT PK_TB_UF
PRIMARY KEY (SIGLA_UF);

CREATE TABLE TB_CIDADE
(
    PID NUMBER NOT NULL,
    COD_IBGE NUMBER,
    CIDADE VARCHAR2(100),
    SIGLA_UF VARCHAR2(2) NOT NULL,
    CIDADE_AREA NUMBER
);

ALTER TABLE TB_CIDADE
ADD CONSTRAINT PK_CIDADE
PRIMARY KEY (PID);

ALTER TABLE TB_CIDADE
ADD CONSTRAINT FK_CIDADE_UF
FOREIGN KEY (SIGLA_UF)
REFERENCES TB_UF(SIGLA_UF);

CREATE TABLE TB_MUNICIPIO
(   PID NUMBER NOT NULL,
    SIGLA_UF VARCHAR2(2) NOT NULL, 
    COD_IBGE VARCHAR2(10) NOT NULL,
    MUNICIPIO VARCHAR2(30) NOT NULL,
    LATITUDE VARCHAR2(30),
    LONGITUDE VARCHAR2(30)
);

ALTER TABLE TB_MUNICIPIO
ADD CONSTRAINT PK_TB_MUNICIPIO
PRIMARY KEY (PID);

ALTER TABLE TB_MUNICIPIO
ADD CONSTRAINT FK_MUNICIPIO_UF
FOREIGN KEY (SIGLA_UF)
REFERENCES TB_UF(SIGLA_UF);


CREATE TABLE TB_BAIRRO
(   PID NUMBER NOT NULL, 
    SIGLA_UF VARCHAR2(2) NOT NULL,
    BAIRRO VARCHAR2(100),
    PID_CIDADE NUMBER NOT NULL,
    CEP VARCHAR2(9),
    LATITUDE VARCHAR2(30),
    LONGITUDE VARCHAR2(30)
);

ALTER TABLE TB_BAIRRO
ADD CONSTRAINT PK_TB_BAIRRO
PRIMARY KEY (PID);

ALTER TABLE TB_BAIRRO
ADD CONSTRAINT FK_BAIRRO_UF
FOREIGN KEY (SIGLA_UF)
REFERENCES TB_UF (SIGLA_UF);

COMMIT;


CREATE TABLE TB_LOGRADOURO
(   PID NUMBER NOT NULL,
    SIGLA_UF VARCHAR2(2) NOT NULL,
    PID_CIDADE NUMBER NOT NULL,
    LOGRADOURO VARCHAR2(100),
    CEP VARCHAR2(9),
    TIPO VARCHAR2(100)
);

ALTER TABLE TB_LOGRADOURO
ADD CONSTRAINT PK_TB_LOGRADOURO
PRIMARY KEY (PID);

ALTER TABLE TB_LOGRADOURO
ADD CONSTRAINT FK_TB_LOGRADOURO_UF
FOREIGN KEY (SIGLA_UF)
REFERENCES TB_UF(SIGLA_UF);

ALTER TABLE TB_LOGRADOURO
ADD CONSTRAINT FK_TB_LOGRADOURO_CIDADE
FOREIGN KEY (PID_CIDADE)
REFERENCES TB_CIDADE (PID);

CREATE TABLE TB_BAIRRO_LOGRADOURO
(   PID NUMBER NOT NULL,
    PID_BAIRRO NUMBER NOT NULL,
    PID_LOGRADOURO NUMBER NOT NULL
);


ALTER TABLE TB_BAIRRO_LOGRADOURO
ADD CONSTRAINT FK_TB_BAIRRO_LOGRADOURO_BAIRRO
FOREIGN KEY (PID_BAIRRO)
REFERENCES TB_BAIRRO (PID);


ALTER TABLE TB_BAIRRO_LOGRADOURO
ADD CONSTRAINT FK_TB_BAIRRO_LOGRADOURO_LOGRADOURO
FOREIGN KEY (PID_LOGRADOURO)
REFERENCES TB_LOGRADOURO (PID);

COMMIT;
-- CLIENTES
CREATE TABLE TB_CLIENTES(
 PID NUMBER NOT NULL,
 NOME VARCHAR2(100),
 GENERO CHAR(1) CHECK (GENERO IN('M','F')),
 DATA_NASCIMENTO DATE,
 IDADE INTEGER
 );
 
 ALTER TABLE TB_CLIENTES
 ADD CONSTRAINT PK_TB_CLIENTES
 PRIMARY KEY(PID);
 