-- sequencial de PID
CREATE OR REPLACE TRIGGER TR_PID_MUNICIPIO
BEFORE INSERT ON TB_MUNICIPIO FOR EACH ROW
BEGIN
    IF (:NEW.PID IS NULL) THEN
        :NEW.PID := SYSTEM.SEQ_PID_MUNICIPIO.NEXTVAL;
    END IF;
END;
/  

COMMIT;
