
CREATE OR REPLACE FUNCTION FNC_INSERIR_CEP_BAIRRO (PCEP_INDEX NUMBER)
RETURN VARCHAR2 IS
    VCEP NUMBER;  
BEGIN
    SELECT CEP INTO VCEP FROM TB_BAIRRO WHERE PID = PCEP_INDEX;
    RETURN VCEP;
END;
/

