CREATE OR REPLACE FUNCTION FNC_FK_PID_CIDADE (PNOME_CIDADE VARCHAR2)
RETURN NUMBER IS
 VPID_CIDADE NUMBER;
BEGIN
    SELECT PID INTO VPID_CIDADE FROM TB_CIDADE WHERE CIDADE = PNOME_CIDADE;
    RETURN VPID_CIDADE;
END;
/


CREATE OR REPLACE FUNCTION FNC_INSERIR_CEP_BAIRRO (PCEP_INDEX NUMBER)
RETURN VARCHAR2 IS
    VCEP NUMBER;  
BEGIN
    SELECT CEP INTO VCEP FROM TB_BAIRRO WHERE PID = PCEP_INDEX;
    RETURN VCEP;
END;
/


CREATE OR REPLACE FUNCTION FNC_INSERIR_CEP_LOGRADOURO (PCEP_INDEX NUMBER)
RETURN VARCHAR2 IS
    VCEP VARCHAR2(9);
BEGIN
    SELECT CEP INTO VCEP FROM TB_LOGRADOURO WHERE PID = PCEP_INDEX;
    
   RETURN VCEP;
END;
/



