ALTER SESSION SET CONTAINER = FREEPDB1;


CREATE USER USERADDRESS 
IDENTIFIED BY ADDRESS123
QUOTA 200M ON SYSTEM;

GRANT CREATE SESSION, CREATE TABLE TO USERADDRESS;


CREATE TABLE USERADDRESS.TB_UF( 
    UF        VARCHAR2(2) NOT NULL,
    COD_IBGE  VARCHAR2(10) NOT NULL, 
    NOME      VARCHAR2(50),
    REGIAO    VARCHAR(20),
    CONSTRAINT PK_UF PRIMARY KEY (UF)
);


CREATE TABLE USERADDRESS.TB_CIDADE(
    ID          NUMBER NOT NULL,
    COD_IBGE    NUMBER,
    CIDADE      VARCHAR2(100),
    UF          VARCHAR2(2) NOT NULL,
    AREA        NUMBER,
    CONSTRAINT PK_CIDADE_ID PRIMARY KEY (ID),
    CONSTRAINT FK_CIDADE_UF FOREIGN KEY(UF) REFERENCES USERADDRESS.TB_UF(UF)
);


CREATE TABLE USERADDRESS.TB_ENDERECO(	
    ID          NUMBER NOT NULL,
    CEP         VARCHAR2(15) NOT NULL, 
	UF          VARCHAR2(2) NOT NULL, 
	ID_CIDADE   NUMBER NOT NULL, 
	BAIRRO      VARCHAR2(200), 
	RUA         VARCHAR2(400), 
    CONSTRAINT PK_ENDERECO_ID PRIMARY KEY (ID),
    CONSTRAINT FK_ENDERECO_UF FOREIGN KEY (UF) REFERENCES USERADDRESS.TB_UF(UF), 
    CONSTRAINT FK_ENDERECO_CIDADE FOREIGN KEY (ID_CIDADE) REFERENCES USERADDRESS.TB_CIDADE(ID) 
);


CREATE TABLE USERADDRESS.TB_MORADORES(
    ID              NUMBER NOT NULL,
    NOME            VARCHAR2(100),
    GENERO          CHAR(1) CHECK (GENERO IN('M','F')),
    DATA_NASCIMENTO DATE,
    CONSTRAINT  PK_MORADOR PRIMARY KEY (ID)
);
 
 