CREATE TABLE TB_CIDADE(
    P_CIDADE NUMBER NOT NULL,
    COD_IBGE NUMBER,
    CIDADE VARCHAR2(100),
    F_UF VARCHAR2(2) NOT NULL,
    CIDADE_AREA NUMBER,
    CONSTRAINT PK_CIDADE PRIMARY KEY (P_CIDADE),
    CONSTRAINT FK_CIDADE_UF FOREIGN KEY(F_UF) REFERENCES TB_UF(P_UF)
);


CREATE SEQUENCE SQ_CIDADE START WITH 1 INCREMENT BY 1;

-- TRIGGER DO PID DE TB_CIDADE
CREATE OR REPLACE TRIGGER TR_CIDADE_PK
BEFORE INSERT ON TB_CIDADE FOR EACH ROW
BEGIN
    IF :NEW.P_CIDADE IS NULL THEN
        :NEW.P_CIDADE := SQ_CIDADE.NEXTVAL;
    END IF;
END;
/  